//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevizaValtoTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevizaValtoTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gesmes:Envelope xmlns:gesmes=&quot;http://www.gesmes.org/xml/2002-08-01&quot; xmlns=&quot;http://www.ecb.int/vocabulary/2002-08-01/eurofxref&quot;&gt;
        ///  &lt;gesmes:subject&gt;Reference rates&lt;/gesmes:subject&gt;
        ///  &lt;gesmes:Sender&gt;
        ///    &lt;gesmes:name&gt;European Central Bank&lt;/gesmes:name&gt;
        ///  &lt;/gesmes:Sender&gt;
        ///  &lt;Cube&gt;
        ///    &lt;CubeROSSZ time=&quot;2022-02-07&quot;&gt;
        ///      &lt;Cube currency=&quot;USD&quot; rate=&quot;1.1447&quot;/&gt;
        ///      &lt;Cube currency=&quot;JPY&quot; rate=&quot;131.59&quot;/&gt;
        ///      &lt;Cube currency=&quot;BGN&quot; rate=&quot;1.9558&quot;/&gt;
        ///      &lt;Cube currency=&quot;CZK&quot; rate=&quot;24.222&quot;/&gt;
        ///      &lt;Cube curr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NincsDatum {
            get {
                return ResourceManager.GetString("NincsDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gesmes:Envelope xmlns:gesmes=&quot;http://www.gesmes.org/xml/2002-08-01&quot; xmlns=&quot;http://www.ecb.int/vocabulary/2002-08-01/eurofxref&quot;&gt;
        ///  &lt;gesmes:subject&gt;Reference rates&lt;/gesmes:subject&gt;
        ///  &lt;gesmes:Sender&gt;
        ///    &lt;gesmes:name&gt;European Central Bank&lt;/gesmes:name&gt;
        ///  &lt;/gesmes:Sender&gt;
        ///  &lt;Cube&gt;
        ///    &lt;Cube time=&quot;2022-02-07&quot;&gt;
        ///      &lt;Cube currency=&quot;USD&quot; rate=&quot;1.1447&quot;/&gt;
        ///      &lt;Cube currency=&quot;JPY&quot; rate=&quot;131.59&quot;/&gt;
        ///      &lt;Cube currency=&quot;BGN&quot; rate=&quot;1.9558&quot;/&gt;
        ///      &lt;Cube currency=&quot;CZK&quot; rate=&quot;24.222&quot;/&gt;
        ///      &lt;Cube currency= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NincsHUF {
            get {
                return ResourceManager.GetString("NincsHUF", resourceCulture);
            }
        }
    }
}
