//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevizaValto.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevizaValto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml.
        /// </summary>
        public static string DevizaXml {
            get {
                return ResourceManager.GetString("DevizaXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A deviza árfolyamokat tartalmazó állomány nem olvasható..
        /// </summary>
        public static string HibaDevizaXMLNemOlvashato {
            get {
                return ResourceManager.GetString("HibaDevizaXMLNemOlvashato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiányzik a Forint árfolyama..
        /// </summary>
        public static string HibaHUFDevizaNincs {
            get {
                return ResourceManager.GetString("HibaHUFDevizaNincs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valószínűleg hibás szerkezetű a deviza állomány..
        /// </summary>
        public static string HibaNincsDatum {
            get {
                return ResourceManager.GetString("HibaNincsDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A deviza értéke 0, így az átváltás nem lehetséges..
        /// </summary>
        public static string HibaNullasDeviza {
            get {
                return ResourceManager.GetString("HibaNullasDeviza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html.
        /// </summary>
        public static string Webhely {
            get {
                return ResourceManager.GetString("Webhely", resourceCulture);
            }
        }
    }
}
